### PR TITLE
Fix quoting and regex parsing for minimization

### LINKED ISSUE #134: coqbot minimize should have proper quoting of the script
Currently the regex at 
https://github.com/coq/bot/blob/b10cfb9dd8aea4eb5865f3d636123f1794312eca/src/bot.ml#L160
will be incorrect if the script contains a backtick (``` ` ```) (it should just look for `@coqbot:? [Mm]inimize` followed by a newline, followed by a line starting with ` ``` `, and then take the script to be all of the lines until the next line starting with ` ``` `).  Additionally, the invocation of the bash script at
https://github.com/coq/bot/blob/b10cfb9dd8aea4eb5865f3d636123f1794312eca/src/git_utils.ml#L120-L121
just sticks the script between single quotes (`'`), which is not proper quoting.  Instead, [`Filename.quote_command`](https://ocaml.org/api/Filename.html#VALquote_command) should be used.

### PR DESCRIPTION
**Pull request by JasonGross**
On top of #112 

Fixes #134

### CODE REVIEW

**Review by Zimmi48 — APPROVED** [review]

File: src/bot.ml [hunk 1]
```diff
@@ -153,98 +166,94 @@ let callback _conn req body =
...
                 ~owner:issue_info.issue.owner ~repo:issue_info.issue.repo
-                (run_coq_minimizer ~script:(Str.matched_group 1 body)
-                   ~comment_thread_id:issue_info.id
+                (run_coq_minimizer ~script ~comment_thread_id:issue_info.id
                    ~comment_author:issue_info.user ~owner:issue_info.issue.owner
                    ~repo:issue_info.issue.repo))
             |> Lwt.async ;
-          Server.respond_string ~status:`OK ~body:"Handling minimization." ()
-      | Ok (signed, CommentCreated comment_info) ->
-          let body = Helpers.trim_comments comment_info.body in
```
Comment (JasonGross) [inline src/bot.ml:175]: Oops, I should not have removed this
